apiVersion: v1
data:
  values.yaml: 'base-key: base-value'
kind: ConfigMap
metadata:
  labels:
    gitops.natron.io/stage: '{stage}-{stage}'
  name: base-values
  namespace: '{deployment}-{stage}-{stage}'
---
apiVersion: v1
data:
  values.yaml: 'deploy-key: deploy-value'
kind: ConfigMap
metadata:
  labels:
    gitops.natron.io/stage: '{stage}-{stage}'
  name: deploy-values
  namespace: '{deployment}-{stage}-{stage}'
---
apiVersion: v1
data:
  values.yaml: 'stage-base-key: stage-base-value'
kind: ConfigMap
metadata:
  labels:
    gitops.natron.io/stage: '{stage}-{stage}'
  name: '{stage}-values'
  namespace: '{deployment}-{stage}-{stage}'
---
apiVersion: v1
data:
  values.yaml: 'stage-base-key: stage-base-value'
kind: ConfigMap
metadata:
  labels:
    gitops.natron.io/stage: '{stage}-{stage}'
  name: '{stage}-{stage}-values'
  namespace: '{deployment}-{stage}-{stage}'
---
apiVersion: v1
data:
  secrets.yaml: YmFzZS1zZWNyZXRrZXk6IGJhc2Utc2VjcmV0dmFsdWU=
kind: Secret
metadata:
  labels:
    gitops.natron.io/stage: '{stage}-{stage}'
  name: base-secrets
  namespace: '{deployment}-{stage}-{stage}'
type: Opaque
---
apiVersion: v1
data:
  secrets.yaml: ZGVwbG95LXNlY3JldGtleTogZGVwbG95LXNlY3JldHZhbHVl
kind: Secret
metadata:
  labels:
    gitops.natron.io/stage: '{stage}-{stage}'
  name: deploy-secrets
  namespace: '{deployment}-{stage}-{stage}'
type: Opaque
---
apiVersion: v1
data:
  secrets.yaml: c3RhZ2UtYmFzZS1zZWNyZXRrZXk6IHN0YWdlLWJhc2Utc2VjcmV0dmFsdWU=
kind: Secret
metadata:
  labels:
    gitops.natron.io/stage: '{stage}-{stage}'
  name: '{stage}-secrets'
  namespace: '{deployment}-{stage}-{stage}'
type: Opaque
---
apiVersion: v1
data:
  secrets.yaml: c3RhZ2UtYmFzZS1zZWNyZXRrZXk6IHN0YWdlLWJhc2Utc2VjcmV0dmFsdWU=
kind: Secret
metadata:
  labels:
    gitops.natron.io/stage: '{stage}-{stage}'
  name: '{stage}-{stage}-secrets'
  namespace: '{deployment}-{stage}-{stage}'
type: Opaque
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    gitops.natron.io/stage: '{stage}-{stage}'
  name: '{application}'
  namespace: '{deployment}-{stage}-{stage}'
spec:
  chart:
    spec:
      chart: '{application-chart}'
      sourceRef:
        kind: HelmRepository
        name: '{application}-charts'
        namespace: '{application}'
  install:
    remediation:
      remediateLastFailure: true
  interval: 10m
  upgrade:
    remediation:
      remediateLastFailure: true
  valuesFrom:
  - kind: ConfigMap
    name: base-values
  - kind: Secret
    name: base-secrets
  - kind: ConfigMap
    name: '{stage}-values'
  - kind: Secret
    name: '{stage}-secrets'
  - kind: ConfigMap
    name: '{stage}-{stage}-values'
  - kind: Secret
    name: '{stage}-{stage}-secrets'
  - kind: ConfigMap
    name: deploy-values
  - kind: Secret
    name: deploy-secrets
