apiVersion: v1
kind: Namespace
metadata:
  labels:
    gitops.natron.io/application: '{application}'
    gitops.natron.io/stage: base
  name: '{deployment}'
---
apiVersion: v1
data:
  values.yaml: 'base-key: base-value'
kind: ConfigMap
metadata:
  labels:
    gitops.natron.io/application: '{application}'
    gitops.natron.io/stage: base
  name: base-values
  namespace: '{deployment}'
---
apiVersion: v1
data:
  values.yaml: 'deploy-key: deploy-value'
kind: ConfigMap
metadata:
  labels:
    gitops.natron.io/stage: base
  name: deploy-values
  namespace: '{deployment}'
---
apiVersion: v1
data:
  secrets.yaml: YmFzZS1zZWNyZXRrZXk6IGJhc2Utc2VjcmV0dmFsdWU=
kind: Secret
metadata:
  labels:
    gitops.natron.io/application: '{application}'
    gitops.natron.io/stage: base
  name: base-secrets
  namespace: '{deployment}'
type: Opaque
---
apiVersion: v1
data:
  secrets.yaml: ZGVwbG95LXNlY3JldGtleTogZGVwbG95LXNlY3JldHZhbHVl
kind: Secret
metadata:
  labels:
    gitops.natron.io/stage: base
  name: deploy-secrets
  namespace: '{deployment}'
type: Opaque
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    gitops.natron.io/application: '{application}'
    gitops.natron.io/stage: base
  name: '{application}'
  namespace: '{deployment}'
spec:
  chart:
    spec:
      chart: '{application-chart}'
      sourceRef:
        kind: HelmRepository
        name: '{application}-charts'
        namespace: '{application}'
  install:
    remediation:
      remediateLastFailure: true
  interval: 10m
  upgrade:
    remediation:
      remediateLastFailure: true
  valuesFrom:
  - kind: ConfigMap
    name: base-values
  - kind: Secret
    name: base-secrets
  - kind: ConfigMap
    name: deploy-values
  - kind: Secret
    name: deploy-secrets
