apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: '{{ .ApplicationName }}-charts'
  namespace: '{{ .ApplicationName }}'
spec:
  interval: 10m0s
  url: https://charts.bitnami.com/bitnami
