apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: '{{ .DeploymentNameWithoutEnding }}'
  namespace: flux-system
spec:
  targetNamespace: '{{ .DeploymentNameWithoutEnding }}'
  interval: 5m0s
  path: {{ .PathFromMomentumRoot }}
  prune: true
  sourceRef:
    kind: GitRepository
    name: '{{ .RepositoryName }}'
