version: '3.5'

services:
  momentum:
    build: .
    # image: ghcr.io/natrontech/momentum:latest
    ports:
      - "8090:8090"
    volumes:
      # * This is the path to the data folder on your local machine
      - $PWD/momentum-backend/pb_data:/app/momentum/pb_data
