apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ns.yaml
- release.yaml
configMapGenerator:
- files:
  - values.yaml
  name: base-values
  options:
    disableNameSuffixHash: true
secretGenerator:
- files:
  - secrets.yaml
  name: base-secrets
  options:
    disableNameSuffixHash: true
labels:
- includeSelectors: true
  pairs:
    gitops.natron.io/application: '{application}'
