apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: to-be-patched
  namespace: argocd
  annotations:
    pref.argocd.argoproj.io/default-view: network
    pref.argocd.argoproj.io/default-pod-sort: parentResource
spec:
  source:
    chart: {{ .HelmChartName }}
    repoURL: {{ .HelmRepoUrl }}
    targetRevision: {{ .HelmChartVersion }}
    helm:
      releaseName: {{ .ApplicationName }}
      valuesObject:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: to-be-patched
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
