apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- application.yaml
labels:
- includeSelectors: true
  pairs:
    gitops.natron.io/application: '{{ .ApplicationName }}'
patches:
  - path: values.yaml
    target:
      kind: Application

