apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: '{application}'
spec:
  interval: '{application-interval}'
  chart:
    spec:
      version: '{application-chart-version}'
      sourceRef:
        kind: HelmRepository
        name: '{application}-charts'
        namespace: '{application}'
  install:
    remediation:
      remediateLastFailure: true
  upgrade:
    remediation:
      remediateLastFailure: true
  valuesFrom:
    - kind: ConfigMap
      name: base-values
    - kind: Secret
      name: base-secrets
    - kind: ConfigMap
      name: deploy-values
    - kind: Secret
      name: deploy-secrets
