apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: '{{ .ApplicationName }}'
spec:
  valuesFrom:
    - kind: ConfigMap
      name: base-values
    - kind: Secret
      name: base-secrets
    - kind: ConfigMap
      name: '{{ .StageName }}-values'
    - kind: Secret
      name: '{{ .StageName }}-secrets'
    - kind: ConfigMap
      name: deploy-values
    - kind: Secret
      name: deploy-secrets
