apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: {{ .DeploymentName }}
spec:
  interval: 5m0s
  path: ./_deploy/{{ .DeploymentName }}/
  prune: true
  sourceRef:
    kind: GitRepository
    name: {{ .RepositoryName }}