apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: '{deployment}'
  namespace: flux-system
spec:
  targetNamespace: '{deployment}'
  interval: 5m0s
  path: ./momentum-root/{application}/_deploy/{deployment}/
  prune: true
  sourceRef:
    kind: GitRepository
    name: momentum
