/**
 * Momentum Core API
 * The momentum core api manages the core structure of momentum
 *
 * The version of the OpenAPI document: early-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModelsDeployment { 
    id?: string;
    name?: string;
    parentStageId?: string;
    repositoryId?: string;
}

