apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../_base/
configMapGenerator:
- files:
  - values.yaml
  name: '{stage}-values'
  options:
    disableNameSuffixHash: true
secretGenerator:
- files:
  - values.yaml=secrets.yaml
  name: '{stage}-secrets'
  options:
    disableNameSuffixHash: true
patches:
  - path: release.yaml
labels:
- includeSelectors: true
  pairs:
    gitops.natron.io/application: '{application}'
    gitops.natron.io/stage: '{stage}'
