apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../_base/release.yaml
configMapGenerator:
- files:
  - ../../_base/values.yaml
  name: base-values
  options:
    disableNameSuffixHash: true
- files:
  - values.yaml
  name: '{stage}-values'
  options:
    disableNameSuffixHash: true
secretGenerator:
- files:
  - ../../_base/secrets.yaml
  name: base-secrets
  options:
    disableNameSuffixHash: true
- files:
  - secrets.yaml
  name: '{stage}-secrets'
  options:
    disableNameSuffixHash: true
patches:
  - path: release.yaml
