apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: '{application}'
spec:
  interval: '{application-interval}'
  chart:
    spec:
      version: '{application-chart-version}'
