apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../_base/
labels:
- includeSelectors: true
  pairs:
    gitops.natron.io/app: "{{ .ApplicationName }}"
patches:
  - path: application.yaml
    target:
      kind: Application
  - path: values.yaml
    target:
      kind: Application