apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ .ApplicationName }}
spec:
  interval: '{{ .ReconcileInterval }}'
  chart:
    spec:
      version: '{{ .ChartVersion }}'
      sourceRef:
        kind: HelmRepository
        name: '{{ .ApplicationName }}-charts'
        namespace: '{{ .ApplicationName }}'
  install:
    remediation:
      remediateLastFailure: true
  upgrade:
    remediation:
      remediateLastFailure: true
  valuesFrom:
    - kind: ConfigMap
      name: base-values
    - kind: Secret
      name: base-secrets
    - kind: ConfigMap
      name: deploy-values
    - kind: Secret
      name: deploy-secrets
